### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ujscjj** [aispeech-lab/WASE#1]
Hi, it is a great job. Could you please update your codes? Thank you very much.

**Comment by haoyz** [comment]
Thx. For some reasons, we will open source in December. Please forgive us.

**Comment by haoyz** [comment]
Thx. For some reasons, we will open source in December. Please forgive us.
Duplicate of #

**Comment by haoyz** [comment]
> Hi, it is a great job. Could you please update your codes? Thank you very much.

Thx. For some reasons, we will open source in December. Please forgive us.

**Comment by haoyz** [comment]
Hi, the code is available in aispeech-lab/WASE_202112.

> Hi, it is a great job. Could you please update your codes? Thank you very much.
